--// Icons — PNG assets hosted on GitHub (loaded via HttpGet)
--// The base URL points to the /assets/ folder in your repo.
--// Change ICON_BASE_URL if you host elsewhere.

local ICON_BASE_URL = "https://raw.githubusercontent.com/Sussyf4/scripttest/main/assets/"

--// All available icons.
--// Format: short-name → PNG filename (no path, just filename).
--// Usage: NovaLib:GetIcon("name") returns the full URL.
NovaLib.Icons = {
	--// Window Controls
	["x"]                   = "x.png",
	["minus"]               = "minus.png",
	["plus"]                = "plus.png",
	["maximize"]            = "maximize.png",
	["maximize-2"]          = "maximize-2.png",
	["minimize"]            = "minimize.png",
	["minimize-2"]          = "minimize-2.png",
	["menu"]                = "menu.png",
	["expand"]              = "expand.png",
	["move-horizontal"]     = "move-horizontal.png",
	["move-vertical"]       = "move-vertical.png",
	["move-diagonal"]       = "move-diagonal.png",
	["move-diagonal-2"]     = "move-diagonal-2.png",

	--// Element Indicators
	["check"]               = "check.png",
	["check-circle"]        = "check-circle.png",
	["check-circle-2"]      = "check-circle-2.png",
	["check-square"]        = "check-square.png",
	["chevron-down"]        = "chevron-down.png",
	["chevron-up"]          = "chevron-up.png",
	["chevron-left"]        = "chevron-left.png",
	["chevron-right"]       = "chevron-right.png",
	["chevron-first"]       = "chevron-first.png",
	["chevron-last"]        = "chevron-last.png",
	["chevrons-down"]       = "chevrons-down.png",
	["chevrons-up"]         = "chevrons-up.png",
	["chevrons-left"]       = "chevrons-left.png",
	["chevrons-right"]      = "chevrons-right.png",
	["chevrons-down-up"]    = "chevrons-down-up.png",
	["chevrons-up-down"]    = "chevrons-up-down.png",
	["chevrons-left-right"] = "chevrons-left-right.png",
	["chevrons-right-left"] = "chevrons-right-left.png",

	--// Notifications & Status
	["info"]                = "info.png",
	["alert-circle"]        = "alert-circle.png",
	["alert-octagon"]       = "alert-octagon.png",
	["alert-triangle"]      = "alert-triangle.png",
	["x-circle"]            = "x-circle.png",
	["minus-circle"]        = "minus-circle.png",
	["plus-circle"]         = "plus-circle.png",
	["plus-square"]         = "plus-square.png",
	["verified"]            = "verified.png",
	["shield"]              = "shield.png",
	["shield-check"]        = "shield-check.png",
	["shield-alert"]        = "shield-alert.png",
	["shield-close"]        = "shield-close.png",

	--// Tabs & Buttons
	["eye"]                 = "eye.png",
	["eye-off"]             = "eye-off.png",
	["settings"]            = "settings.png",
	["settings-2"]          = "settings-2.png",
	["cog"]                 = "cog.png",
	["home"]                = "home.png",
	["search"]              = "search.png",
	["filter"]              = "filter.png",
	["bell"]                = "bell.png",
	["bell-off"]            = "bell-off.png",
	["star"]                = "star.png",
	["heart"]               = "heart.png",
	["sparkles"]            = "star.png",
	["flame"]               = "flame.png",
	["lightbulb"]           = "lightbulb.png",
	["lightbulb-off"]       = "lightbulb-off.png",
	["gem"]                 = "gem.png",
	["rocket"]              = "rocket.png",
	["sword"]               = "sword.png",
	["wand"]                = "wand.png",
	["skull"]               = "skull.png",
	["bomb"]                = "bomb.png",
	["bug"]                 = "bug.png",

	--// User & People
	["user"]                = "user.png",
	["users"]               = "users.png",
	["user-plus"]           = "user-plus.png",
	["user-minus"]          = "user-minus.png",
	["user-check"]          = "user-check.png",
	["bot"]                 = "bot.png",

	--// Actions
	["save"]                = "save.png",
	["download"]            = "download.png",
	["download-cloud"]      = "download-cloud.png",
	["upload"]              = "upload.png",
	["trash"]               = "trash.png",
	["trash-2"]             = "trash-2.png",
	["edit"]                = "edit.png",
	["edit-2"]              = "edit-2.png",
	["edit-3"]              = "edit-3.png",
	["copy"]                = "copy.png",
	["scissors"]            = "scissors.png",
	["clipboard"]           = "clipboard.png",
	["clipboard-check"]     = "clipboard-check.png",
	["clipboard-copy"]      = "clipboard-copy.png",
	["clipboard-x"]         = "clipboard-x.png",
	["undo"]                = "undo.png",
	["undo-2"]              = "undo-2.png",
	["redo"]                = "redo.png",
	["redo-2"]              = "redo-2.png",
	["refresh-cw"]          = "refresh-cw.png",
	["delete"]              = "delete.png",
	["eraser"]              = "eraser.png",
	["import"]              = "import.png",

	--// Arrows & Navigation
	["arrow-up"]            = "arrow-up.png",
	["arrow-down"]          = "arrow-down.png",
	["arrow-left"]          = "arrow-left.png",
	["arrow-right"]         = "arrow-right.png",
	["arrow-up-left"]       = "arrow-up-left.png",
	["arrow-up-right"]      = "arrow-up-right.png",
	["arrow-down-left"]     = "arrow-down-left.png",
	["arrow-down-right"]    = "arrow-down-right.png",
	["arrow-up-circle"]     = "arrow-up-circle.png",
	["arrow-down-circle"]   = "arrow-down-circle.png",
	["arrow-left-circle"]   = "arrow-left-circle.png",
	["arrow-right-circle"]  = "arrow-right-circle.png",
	["arrow-left-right"]    = "arrow-left-right.png",
	["arrow-up-down"]       = "arrow-up-down.png",
	["arrow-big-left"]      = "arrow-big-left.png",
	["arrow-big-right"]     = "arrow-big-right.png",
	["arrow-big-up"]        = "arrow-big-up.png",
	["corner-up-left"]      = "corner-up-left.png",
	["corner-up-right"]     = "corner-up-right.png",
	["corner-down-left"]    = "corner-down-left.png",
	["corner-down-right"]   = "corner-down-right.png",
	["corner-left-up"]      = "corner-left-up.png",
	["corner-left-down"]    = "corner-left-down.png",
	["corner-right-up"]     = "corner-right-up.png",
	["corner-right-down"]   = "corner-right-down.png",
	["navigation"]          = "navigation.png",
	["navigation-2"]        = "navigation-2.png",
	["compass"]             = "compass.png",
	["locate"]              = "locate.png",
	["locate-fixed"]        = "locate-fixed.png",
	["locate-off"]          = "locate-off.png",
	["map"]                 = "map.png",
	["crosshair"]           = "crosshair.png",
	["target"]              = "target.png",
	["focus"]               = "focus.png",
	["mouse-pointer"]       = "mouse-pointer-2.png",
	["mouse-pointer-click"] = "mouse-pointer-click.png",

	--// Files & Folders
	["file"]                = "file.png",
	["folder"]              = "folder.png",
	["folder-open"]         = "folder-open.png",
	["image"]               = "image.png",
	["link"]                = "link.png",
	["link-2"]              = "link-2.png",
	["link-2-off"]          = "link-2-off.png",
	["unlink"]              = "unlink.png",
	["unlink-2"]            = "unlink-2.png",
	["external-link"]       = "external-link.png",
	["inbox"]               = "inbox.png",

	--// Communication
	["message-circle"]      = "message-circle.png",
	["message-square"]      = "message-square.png",
	["phone"]               = "phone.png",
	["mail"]                = "mail.png",
	["mail-open"]           = "mail-open.png",
	["send"]                = "send.png",
	["share"]               = "share.png",
	["share-2"]             = "share-2.png",

	--// Scheduling & Time
	["calendar"]            = "calendar.png",
	["clock"]               = "clock.png",
	["alarm-check"]         = "alarm-check.png",
	["alarm-clock"]         = "alarm-clock.png",
	["alarm-clock-off"]     = "alarm-clock-off.png",
	["alarm-minus"]         = "alarm-minus.png",
	["alarm-plus"]          = "alarm-plus.png",

	--// Labels & Tags
	["tag"]                 = "tag.png",
	["bookmark"]            = "bookmark.png",
	["flag"]                = "flag.png",
	["pin"]                 = "pin.png",

	--// Media & Playback
	["play"]                = "play.png",
	["pause"]               = "pause.png",
	["volume"]              = "volume.png",
	["mic"]                 = "mic.png",
	["camera"]              = "camera.png",
	["rss"]                 = "rss.png",

	--// Data & Infrastructure
	["database"]            = "database.png",
	["server"]              = "server.png",
	["server-cog"]          = "server-cog.png",
	["server-crash"]        = "server-crash.png",
	["server-off"]          = "server-off.png",
	["hard-drive"]          = "hard-drive.png",
	["cpu"]                 = "cpu.png",
	["terminal"]            = "terminal.png",
	["code"]                = "code.png",
	["code-2"]              = "code-2.png",
	["command"]             = "command.png",
	["key"]                 = "key.png",
	["fingerprint"]         = "fingerprint.png",
	["lock"]                = "lock.png",
	["unlock"]              = "unlock.png",
	["wifi"]                = "wifi.png",
	["wifi-off"]            = "wifi-off.png",
	["bluetooth"]           = "bluetooth.png",
	["signal"]              = "signal.png",
	["signal-high"]         = "signal-high.png",
	["signal-medium"]       = "signal-medium.png",
	["signal-low"]          = "signal-low.png",
	["signal-zero"]         = "signal-zero.png",
	["cloud"]               = "cloud.png",
	["cloud-cog"]           = "cloud-cog.png",
	["cloud-drizzle"]       = "cloud-drizzle.png",
	["cloud-fog"]           = "cloud-fog.png",
	["cloud-hail"]          = "cloud-hail.png",
	["cloud-lightning"]     = "cloud-lightning.png",
	["cloud-moon"]          = "cloud-moon.png",
	["cloud-moon-rain"]     = "cloud-moon-rain.png",
	["cloud-off"]           = "cloud-off.png",
	["cloud-rain"]          = "cloud-rain.png",
	["cloud-rain-wind"]     = "cloud-rain-wind.png",
	["cloud-snow"]          = "cloud-snow.png",
	["cloud-sun"]           = "cloud-sun.png",
	["cloud-sun-rain"]      = "cloud-sun-rain.png",
	["cloudy"]              = "cloudy.png",
	["snowflake"]           = "snowflake.png",
	["sun"]                 = "sun.png",
	["sun-dim"]             = "sun-dim.png",
	["moon"]                = "moon.png",
	["power"]               = "power.png",
	["power-off"]           = "power-off.png",
	["electricity"]         = "electricity.png",
	["electricity-off"]     = "electricity-off.png",
	["loader"]              = "loader.png",
	["loader-2"]            = "loader-2.png",

	--// Layout & UI
	["layers"]              = "layers.png",
	["layout"]              = "layout.png",
	["grid"]                = "grid.png",
	["list"]                = "list.png",
	["list-ordered"]        = "list-ordered.png",
	["sliders"]             = "sliders.png",
	["sliders-horizontal"]  = "sliders-horizontal.png",
	["toggle-left"]         = "toggle-left.png",
	["toggle-right"]        = "toggle-right.png",
	["separator-horizontal"] = "separator-horizontal.png",
	["separator-vertical"]  = "separator-vertical.png",
	["sort-asc"]            = "sort-asc.png",
	["sort-desc"]           = "sort-desc.png",
	["scroll"]              = "scroll.png",

	--// Misc
	["accessibility"]       = "accessibility.png",
	["activity"]            = "activity.png",
	["baseline"]            = "baseline.png",
	["bus"]                 = "bus.png",
	["cake"]                = "cake.png",
	["clover"]              = "clover.png",
	["coffee"]              = "coffee.png",
	["copyleft"]            = "copyleft.png",
	["copyright"]           = "copyright.png",
	["crop"]                = "crop.png",
	["gamepad-2"]           = "gamepad-2.png",
	["globe"]               = "globe.png",
	["globe-2"]             = "globe-2.png",
	["inspect"]             = "inspect.png",
	["log-in"]              = "log-in.png",
	["log-out"]             = "log-out.png",
	["package"]             = "package-2.png",
	["palette"]             = "palette.png",
	["plane"]               = "plane.png",
	["wrench"]              = "wrench.png",
	["circle"]              = "circle.png",
	["circle-dot"]          = "circle-dot.png",
	["circle-ellipsis"]     = "circle-ellipsis.png",
	["circle-slashed"]      = "circle-slashed.png",
	["box"]                 = "box.png",
	["boxes"]               = "boxes.png",
	["box-select"]          = "box-select.png",
	["alert-octagon"]       = "alert-octagon.png",
}

--// Base URL setter (call before CreateWindow if you self-host)
function NovaLib:SetIconBaseURL(url)
	ICON_BASE_URL = url
end

function NovaLib:GetIcon(name)
	if not name then return nil end
	-- If it's already a full URL or rbxassetid, pass through
	if name:sub(1, 4) == "http" or name:sub(1, 7) == "rbxasset" then
		return name
	end
	local filename = NovaLib.Icons[name]
	if not filename then return nil end
	return ICON_BASE_URL .. filename
end
